# Generated by Django 3.2.7 on 2021-11-08 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_socailmedialinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAds',
        ),
    ]
