# Generated by Django 3.2.7 on 2021-11-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_eventguest1_eventguest2_eventguest3'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guest1_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='guest2_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='guest3_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_1_designation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_2_designation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='guest_3_designation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='writer',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
