# Generated by Django 3.2.7 on 2021-11-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211109_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_defualt_img',
            field=models.ImageField(blank=True, null=True, upload_to='Event_default_img'),
        ),
    ]
