# Generated by Django 3.2.7 on 2021-11-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_event_defualt_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=255)),
                ('floor_no', models.CharField(default='', max_length=255)),
                ('product_person_type', models.CharField(choices=[('woman', 'Woman'), ('man', "Man's"), ('kids', "Kid's"), ('kids', "Kid's"), ('others', 'Others')], default='', max_length=255)),
                ('store_website_link', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
