# Generated by Django 3.2.7 on 2021-11-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_img',
            field=models.ImageField(blank=True, null=True, upload_to='store_img'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_person_type',
            field=models.CharField(choices=[('woman', 'Woman'), ('man', "Man's"), ('kids', "Kid's"), ('toys', "Toy's"), ('others', 'Others')], default='', max_length=255),
        ),
    ]
