# Generated by Django 3.2.7 on 2021-11-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211109_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurants_img', models.ImageField(blank=True, null=True, upload_to='restaurants_img')),
                ('name', models.CharField(default='', max_length=255)),
                ('floor_no', models.CharField(default='', max_length=255)),
                ('resrants_website_link', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
