# Generated by Django 3.2.7 on 2021-11-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='banner')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
