# Generated by Django 3.2.7 on 2021-11-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0010_auto_20211109_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
