# Generated by Django 3.2.7 on 2021-11-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0012_bookappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date_choice_1', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date_choice_2', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('date_choice_3', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('subject', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('msg', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
