# Generated by Django 3.2.7 on 2021-11-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0013_bookingappointmentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='floor_details')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[(1, '1st Floor'), (2, '2nd Floor'), (3, '3rd Floor'), (4, '4th Floor'), (5, '5th Floor'), (6, '6th Floor'), (7, '7th Floor'), (8, '8th Floor'), (9, '9th Floor'), (10, '10th Floor'), (11, '11th Floor'), (12, '12th Floor'), (13, 'th Floor'), (14, '14th Floor')], default='', max_length=255)),
            ],
        ),
    ]
