# Generated by Django 3.2.7 on 2021-11-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0014_floordetails_floorlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='floordetails',
            name='floor_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminPanel.floorlist'),
        ),
    ]
