# Generated by Django 3.2.7 on 2021-11-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0016_alter_floorlist_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorlist',
            name='floor_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
